### ISSUE TITLE
1 Map

### ISSUE THREAD

**Issue by MateLoncar** [MateLoncar/capstone-project#3]
## Value proposition

As a user of the world map app,
I want to be able to see a custom world map,
in order to visualize and explore data related to different regions and countries.

## Description

![World Map](https://user-images.githubusercontent.com/80695635/233298357-8bc92f70-674b-4ccd-b7f7-fd79e3ce5238.jpg)

The wireframe shows a world map interface that displays various regions and countries. 

## Acceptance criteria

- [ ] The user can see world map

## Tasks

- [ ] Research and select a suitable mapping API
- [ ]  Create map component
- [ ]  Add map component to index-page

Size: M

**Comment by BenRodProd** [comment]
I think the image in the description should have mobile format?

**Comment by shebtastic** [comment]
I think this would be a great feature, but I would recommend not to start with a heavily interactive component as the first user story.

Since the simplest structure and approach to get started with CRUD operations could be textbased, maybe reserve this story for a later sprint.
