### ISSUE TITLE
2 Map Zoom

### ISSUE THREAD

**Issue by MateLoncar** [MateLoncar/capstone-project#4]
## Value proposition

As a user of the world map app,
I want to be able to see a custom world map,
in order to make zoom in use.

## Description

The user will be able to interact with the map by zooming in and out, scrolling, and clicking on individual regions and countries. The custom map will feature different color schemes and data overlays based on the user's preferences.

## Acceptance criteria

- [ ] The user can zoom in and out of the map interface
- [ ] The user can scroll the map to explore different regions and countries

## Tasks

- [ ]  Test the functionality of the zoom, scroll, and click interactions

Size: S
