### ISSUE TITLE
3. Header and search bar

### ISSUE THREAD

**Issue by MateLoncar** [MateLoncar/capstone-project#5]
## Value proposition

As a user,
I want to see a header with the title "World App Map" and a search bar,
So that I can quickly search and navigate the app.

## Description

The user wants to see a header at the top of the app's interface that displays the title "World App Map" and includes a search bar. This will allow them to easily search for and find the items they are looking for within the app.

## Acceptance criteria

- [ ] The header displays the title "World App Map"
- [ ] The header includes a search bar

## Tasks

- [ ] Design and implement the header with the title "World App Map"
- [ ] Design and implement the search bar within the header

Size: S
