### ISSUE TITLE
4 Search bar functionality

### ISSUE THREAD

**Issue by MateLoncar** [MateLoncar/capstone-project#6]
## Value proposition

As a user,
I want to be able to use a search bar within the app,
So that I can easily find the items I am looking for.

## Description

![Searchbar](https://user-images.githubusercontent.com/80695635/233302437-0da12c93-ea3e-44df-a639-7e05f0b9772b.jpg)

The user wants to be able to use a search bar within the app to quickly search for items. The search bar should be functional and allow the user to easily find the items they are looking for.

## Acceptance criteria

- [ ] The search bar is functional
- [ ]  The search bar allows users to search for items within the app

## Tasks

- [ ] Implement search functionality to allow users to search for items within the app.

Size: S
