### ISSUE TITLE
5 Pin

### ISSUE THREAD

**Issue by MateLoncar** [MateLoncar/capstone-project#7]
## Value proposition

As a user,
I want to add and delete multiple markers on the map.
So that I can easily mark a location of interest.
## Description

![Pin](https://user-images.githubusercontent.com/80695635/233305962-267ca149-cc58-49d7-a971-48ad00aa5b6a.jpg)

The user wants to be able to drop a pin on the map at any location of their choosing. This will allow them to easily mark or delete a location of interest, such as a restaurant or a place to visit or already visited.

## Acceptance criteria

- [ ] The user should be able to add a new marker by clicking on the map.
- [ ] The new marker should be displayed on the map with a popup that shows its location.
- [ ] The user should be able to delete a marker by clicking on it.
- [ ] A confirmation dialog should be displayed before the marker is deleted to prevent accidental deletion.
- [ ] The deleted marker should be removed from the map.

## Tasks

- [ ]  Create a function to add a new marker to the map when the user clicks on it.
- [ ] Decide on the design and content of the marker popup.
- [ ] Implement a function to delete a marker when the user clicks on it.
- [ ] Create a confirmation dialog to prevent accidental deletion.
- [ ] Update the map display to remove the deleted marker.

Size: L

**Comment by onemanwenttomow** [comment]
Is the goal to have multiple markers on the map? 

If so i would create a user story for displaying some initial markers. That way you can decide on how each marker looks (i.e if you use a Popup). 

At the moment i am missing the detailed task for how the user would delete the Marker.
