### ISSUE TITLE
6 Marking Location Visits

### ISSUE THREAD

**Issue by MateLoncar** [MateLoncar/capstone-project#8]
## Value proposition

As a user,
As a user, I want to be able to filter the markers on the map based on my preference.
So that I can keep track of the places I have been to.

## Description

![Question](https://user-images.githubusercontent.com/80695635/233308869-3ee2217e-a1cd-4168-a60b-dc198aaa44eb.png)

The user wants to be able to indicate whether they have visited a location or not, after dropping a pin on the map. This will allow them to keep track of the places they have been to and the places they still want to visit.

## Acceptance criteria

- [ ] The user should be able to filter the markers based on their preference, such as "visited", "want to visit", or "all".
- [ ]  When the user selects a filter, only the markers that match their preference should be displayed on the map.
- [ ] The user should be able to toggle between different filters and see the corresponding markers.
- [ ] If the user clicks on the "want to visit" button, it should change in style to indicate that it has been selected.
- [ ] If the user clicks on the "visited" button, it should change in style to indicate that it has been selected.
- [ ] The user should be able to click on both buttons to select both preferences.

## Tasks

- [ ]  Implement a function to filter the markers based on the user's preference.
- [ ]  Create buttons for "visited", "want to visit", and "all".
- [ ]  Implement a function to toggle between different filters and show the corresponding markers.
- [ ]  Style the buttons to indicate when they have been selected.
- [ ]  Allow the user to select both preferences.

Size: XL

**Comment by onemanwenttomow** [comment]
> Ensure that the user can easily see which locations they have visited and which ones they have not

At the moment i am not sure how this part of the User Story is to be implemented? Will there be something for the user to click on so that some of the Markers then disappear? And then re-appear when they click on it again? Does this mean that each marker can be in 1 of 3 different states? i.e. 
* no info
* want to visit
* visited

If the user clicks on the "I want to go there" button, does the button change in style?
If the user clicks on the "I was there" button, does this button also change style?
Can the user click on both buttons? i.e. they want to go there, but they have also been there.
