### ISSUE TITLE
7 Leave Experiences and Recommendations for Visited Locations

### ISSUE THREAD

**Issue by MateLoncar** [MateLoncar/capstone-project#9]
## Value proposition

As a user,
I want to be able to leave my own experiences and recommendations for locations that I have marked as "visited" on the map,
So that I can share my insights with other users and help them plan their travels.

## Description

![Experience](https://user-images.githubusercontent.com/80695635/233380244-95d14ffd-f133-464e-ad2a-7b4515f214b2.png)

The user wants to be able to leave their own experiences and recommendations for locations that they have marked as "visited" on the map. This will allow them to share their insights and recommendations with other users, and contribute to a community of users who are passionate about travel and exploration.

## Acceptance criteria

- [ ] The user can leave their own experiences and recommendations for a location that they have marked as "visited"

- [ ] The user can leave feedback on different aspects of the location, such as restaurants, hotels, monuments, etc.

- [ ] Other users can view the experiences and recommendations left by the user

## Tasks

- [ ] Design and implement the ability for users to leave their own experiences and recommendations for a location that they have marked as "visited"
- [ ] Design and implement a feedback system for different aspects of the location, such as restaurants, hotels, monuments, etc.
- [ ] Ensure that other users can view the experiences and recommendations left by the user

Size: L

**Comment by botacode-gh** [comment]
LGTM
